version: "3.9"

services:
  liteforum:
    build: .
    restart: always
    depends_on:
      - postgres
      - meilisearch
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/postgres
      MEILI_SEARCH_URL: http://meilisearch:7700

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  meilisearch:
    image: getmeili/meilisearch
    restart: always
